package at.matscheko.intentions.core

/**
 * Built-in autocomplete suggestions for the editor, carried over verbatim from
 * the original app's `res/values/arrays.xml`. These seed the action / category /
 * extra-name dropdowns even before the device's installed apps are scanned.
 */
object IntentSuggestions {

    val actions: List<String> = listOf(
        "android.intent.action.MAIN",
        "android.intent.action.VIEW",
        "android.intent.action.ATTACH_DATA",
        "android.intent.action.EDIT",
        "android.intent.action.PICK",
        "android.intent.action.CHOOSER",
        "android.intent.action.GET_CONTENT",
        "android.intent.action.DIAL",
        "android.intent.action.CALL",
        "android.intent.action.SEND",
        "android.intent.action.SENDTO",
        "android.intent.action.SEND_MULTIPLE",
        "android.intent.action.ANSWER",
        "android.intent.action.INSERT",
        "android.intent.action.DELETE",
        "android.intent.action.RUN",
        "android.intent.action.SYNC",
        "android.intent.action.PICK_ACTIVITY",
        "android.intent.action.SEARCH",
        "android.intent.action.WEB_SEARCH",
        "android.intent.action.FACTORY_TEST",
        "android.intent.action.CALL_BUTTON",
        "android.intent.action.CREATE_SHORTCUT",
        "android.intent.action.SET_WALLPAPER",
        "android.intent.action.BOOT_COMPLETED",
        "android.intent.action.POWER_CONNECTED",
        "android.intent.action.POWER_DISCONNECTED",
        "android.intent.action.SCREEN_ON",
        "android.intent.action.SCREEN_OFF",
        "android.intent.action.BATTERY_LOW",
        "android.intent.action.BATTERY_OKAY",
        "android.intent.action.HEADSET_PLUG",
        "android.intent.action.MEDIA_BUTTON",
        "android.intent.action.CAMERA_BUTTON",
        "android.intent.action.DATE_CHANGED",
        "android.intent.action.TIME_SET",
        "android.intent.action.TIMEZONE_CHANGED",
        "android.intent.action.LOCALE_CHANGED",
        "android.intent.action.CONFIGURATION_CHANGED",
        "android.intent.action.PACKAGE_ADDED",
        "android.intent.action.PACKAGE_REMOVED",
        "android.intent.action.PACKAGE_CHANGED",
        "android.intent.action.PACKAGE_REPLACED",
        "android.intent.action.USER_PRESENT",
        "android.intent.action.AIRPLANE_MODE",
        "android.intent.action.PROVIDER_CHANGED",
        "android.provider.Telephony.SMS_RECEIVED",
        "android.media.RINGER_MODE_CHANGED",
        "android.net.wifi.STATE_CHANGE",
        "android.net.wifi.WIFI_STATE_CHANGED",
    )

    val categories: List<String> = listOf(
        "android.intent.category.DEFAULT",
        "android.intent.category.BROWSABLE",
        "android.intent.category.LAUNCHER",
        "android.intent.category.HOME",
        "android.intent.category.INFO",
        "android.intent.category.PREFERENCE",
        "android.intent.category.ALTERNATIVE",
        "android.intent.category.SELECTED_ALTERNATIVE",
        "android.intent.category.TAB",
        "android.intent.category.OPENABLE",
        "android.intent.category.EMBED",
        "android.intent.category.TEST",
        "android.intent.category.UNIT_TEST",
        "android.intent.category.SAMPLE_CODE",
        "android.intent.category.CAR_DOCK",
        "android.intent.category.DESK_DOCK",
        "android.intent.category.MONKEY",
        "android.intent.category.DEVELOPMENT_PREFERENCE",
    )

    val extraNames: List<String> = listOf(
        "android.intent.extra.TEXT",
        "android.intent.extra.SUBJECT",
        "android.intent.extra.STREAM",
        "android.intent.extra.EMAIL",
        "android.intent.extra.CC",
        "android.intent.extra.BCC",
        "android.intent.extra.TITLE",
        "android.intent.extra.INTENT",
        "android.intent.extra.TEMPLATE",
        "android.intent.extra.KEY_EVENT",
        "android.intent.extra.PHONE_NUMBER",
        "android.intent.extra.UID",
        "android.intent.extra.DONT_KILL_APP",
        "android.intent.extra.shortcut.INTENT",
        "android.intent.extra.shortcut.NAME",
        "android.intent.extra.shortcut.ICON",
        "android.intent.extra.shortcut.ICON_RESOURCE",
    )
}
